'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AssetDetails
    
    '''<summary>
    '''AssetImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AssetImage As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''AssetNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AssetNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OwnerLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OwnerLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TypeLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LocationLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LocationLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CreationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreationDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PriceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PriceLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''IncomeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IncomeLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''StatusLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SUnitsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SUnitsLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SRentLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SRentLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RoomUnitLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoomUnitLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ChairsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChairsLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BR1UnitsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BR1UnitsLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BR1RentLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BR1RentLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SuiteUnitsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SuiteUnitsLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AvgSpendingLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AvgSpendingLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BR2UnitsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BR2UnitsLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BR2RentLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BR2RentLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RoomRateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoomRateLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CustomersPerHour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomersPerHour As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BR3UnitsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BR3UnitsLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BR3RentLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BR3RentLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SuiteRateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SuiteRateLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''HoursOpenLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HoursOpenLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PHUnitsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PHUnitsLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PHRentLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PHRentLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''MiscIncomeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MiscIncomeLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LastModDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LastModDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CoordinateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CoordinateLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''XDimensionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XDimensionLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''YDimensionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YDimensionLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ZDimensionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ZDimensionLabel As Global.System.Web.UI.WebControls.Label
End Class
