'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AssetForm
    
    '''<summary>
    '''FormTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AssetID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AssetID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AssetNametextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AssetNametextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Ownertextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Ownertextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''OwnerIDTextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OwnerIDTextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Districttextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Districttextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CityTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CityTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Pricetextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pricetextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Incometextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Incometextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Statustextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Statustextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ImageURLTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageURLTextBox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TypeDropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TypeDropdown As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''SUnitstextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SUnitstextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''SRenttextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SRenttextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RoomUnittextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoomUnittextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Chairstextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Chairstextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BR1Unitstextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BR1Unitstextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BR1Renttextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BR1Renttextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''SuiteUnitstextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SuiteUnitstextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''AvgSpendingtextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AvgSpendingtextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BR2Unitstextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BR2Unitstextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BR2Renttextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BR2Renttextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RoomRatetextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RoomRatetextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CustomersPerHour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomersPerHour As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BR3Unitstextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BR3Unitstextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BR3Renttextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BR3Renttextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''SuiteRatetextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SuiteRatetextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''HoursOpentextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HoursOpentextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''PHUnitstextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PHUnitstextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''PHRenttextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PHRenttextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''MiscIncometextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MiscIncometextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Coordinatetextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Coordinatetextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''XDimensiontextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents XDimensiontextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''YDimensiontextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YDimensiontextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ZDimensiontextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ZDimensiontextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CreateModBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateModBtn As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''CancelBTN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelBTN As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''NotifPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NotifPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''NotifLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NotifLabel As Global.System.Web.UI.WebControls.Label
End Class
